tasks:
  - name: Installazione Angular CLI e Pandas
    init: |
      npm install -g @angular/cli@16
      pip install pandas flask flask_cors pymongo 

ports:
  - port: 5000
    onOpen: open-preview
    visibility: public